version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: cockroachdb/cockroach:latest
    command: start --insecure
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.3"
          memory: 300M
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:
